### ISSUE TITLE
Event: undefined KeyboardEvent values.

### ISSUE THREAD

**Issue by 4silvertooth** [c-smile/sciter-js-sdk#21]
```html
<html lang="en">
<head>
	<meta charset='utf-8'>
</head>
<body>
  <input placeholder="Enter some text" name="name"/>
  <script>

    const input = document.querySelector('input');
    input.addEventListener('keydown', checkValue);
    input.addEventListener('keyup', checkValue);
    input.addEventListener('keypress', checkValue);

    function checkValue(e) {
      console.log(e.type, e.key, e.keyCode);
    }
  </script>  
</body>
</html>
```

The value of e.key or e.keyCode for the test above is undefined, when we press any key in the input.

**Comment by jsprog** [comment]
- KeyboardEvent is missing
- MouseEvent is missing
- element.click() is missing
I already had a recommendation  [https://github.com/c-smile/sciter-js-sdk/issues/10#issuecomment-731483000](https://github.com/c-smile/sciter-js-sdk/issues/10#issuecomment-731483000) for allowing inputs for non trusted keyboard events and It may help with barcode scanners.

I'll try to share the recommendation in details after finishing with the kick start for sciter.js and svelte
- https://github.com/c-smile/sciter-js-sdk/issues/10#issuecomment-731592544
- [https://github.com/jsprog/sciterjs-svelte3-template](https://github.com/jsprog/sciterjs-svelte3-template)

@4silvertooth: You may need to highlight your code blocks [https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks)

**Comment by c-smile** [comment]
Just in case: I am not going to define [whole bunch of event types](https://developer.mozilla.org/en-US/docs/Web/API/Event#Introduction). At least not at this point.  Instead, Event class will be universally duck typed - include most used properties: event.key, event.code, event.x , event.y, etc.

I may add `element.click()` but it is not clear how it is different from `element.dispatchEvent(new Event("click", {bubbles:true}));` , seems like the same thing, no?

**Comment by jsprog** [comment]
I think that your on the right track trying to bring features by avoiding unnecessary duplicates. Even your recommendation for triggering click is much better and allow more control on the click coordinate. I had to use it more that a year ago to get around some bugs (quasar button) to make sure the ripples were originating from the center when triggered for user feedback.

 Anyway, I had to write something for some reasons:
- I already kept quiet about them for some time due to giving priority to other stuff.
- The moment someone started to write about **input events**, I had to write something to keep our efforts about **them** focused in this issue instead of everyone creating a separate issue for every missing feature.

**input events**: I mean events related to user interaction.

Maybe next time, I'll be having a discussion about [event.isTrusted](https://www.w3.org/TR/uievents/#trusted-events). But let's focus about what's more important first.

**Comment by jsprog** [comment]
The kick start for svelte with Sciter.js mentioned above is ready and all the instruction are detailed:
* [https://github.com/jsprog/sciterjs-svelte-template](https://github.com/jsprog/sciterjs-svelte-template)
* [https://github.com/jsprog/sciterjs-svelte-template/blob/main/svelte_to_sciterjs_startup_instructions.md](https://github.com/jsprog/sciterjs-svelte-template/blob/main/svelte_to_sciterjs_startup_instructions.md)

**Comment by 4silvertooth** [comment]
Why so many pollyfills, shouldn't it be just a single pollyfill-sciter.js, pollyfill-svelte and pollyfill-livereload doesn't make any sense.

**Comment by jsprog** [comment]
In fact, I'm importing only './polyfills' from the `main.js` to bring the other polyfills. The file `./polyfills/index.js` is the one responsible to import all other files for polyfills. Doing this won't hurt, but is better for these reasons:
* This helps keeping structure in your project.
* This template is available publicly and doing this, others should be able to understand the parts requiring these polyfills.
* By following some guidelines like this, you should be able to create re-usable polyfills, and you won't struggle when moving them between projects or sharing them with others.

**Comment by c-smile** [comment]
I think it should be just one css file with definitions like:

```css
   @media sciter {
      html { aspect: RuntimePolyfils url(polyfills/core.js); }
     
      /* elements that need special treatments */
      iframe { prototype: HTMLIFrameElement url(polyfills/iframe.js); }
      form { prototype: HTMLFormElement url(polyfills/form.js); }
      ...
   }
```
In this case that CSS be appended to Master CSS using Sciter API.

And so user's documents can be loaded as the are - without any mentioning of polyfills at all.

**Comment by jsprog** [comment]
With a  **background in web development**, I'm only used to import styles from other style sheets or scripts, not importing scripts from style sheets.

After reading your post several times, I think I understand what you're trying to achieve, but not sure if I understand this very well.

> **In this case that CSS can be appended to Master CSS** using Sciter API.

We're ending with just one CSS file containing all the styles.

> In this case that CSS can be appended to Master CSS using **Sciter API**.

Even rollup and postcss could do even more than this. Likely, you're trying to cover everyone even the ones not using bundlers.

> And so user's documents can be loaded as they are - without any mentioning of polyfills at all.

Anyone should be able to start coding without reading too much information, or having to figure out which polyfills are needed.

>Benefits of this approach is that particular element type handlers/drivers will be loaded on demand - only if they are used.

We don't need to figure out which polyfills are needed by the app. And we should allow the app to start as fast as possible without delaying it with tons of polyfills not needed for the early rendering.

> That's assuming Sciter will have all base types like Element(ext Node), Text(ext Node), Comment(ext Node), Node.

Paraphrasing this may help me to understand.

**The Conclusion about Polyfills:**
- They should be provided in a generic way to be used by everyone.
- They should be provided in a the most efficient way to programmers and runtime.
- We still need many files for the polyfills, but not sure if some of them are to be part of the SDK

**Comment by c-smile** [comment]
> not importing scripts from style sheets.

Yeah, how quickly we've forgot [`behavior` property](https://stackoverflow.com/questions/26339276/what-is-behavior-url-property-in-css/26339363).

Scripting variants of it are [`prototype` and `aspect` properties in Sciter](https://sciter.com/sciter-declarative-behavior-assignment-by-css-prototype-and-aspect-properties/). 

These things make exceptional sense in desktop environment. Yet in polyfill cases.

Conceptually `prototype` is a WebComponent feature.

WebComponent approach is plainly ugly.

In order to start using web components you will need to load all your components upfront using [CustomElementRegistry](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define).  That is far from being a modular approach.

See first that [nightmarish sample](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#Examples). It starts from code that populates DOM and adds CSS. 

In Sciter that can be achieved by CSS.

```css
popup-info  {
   prototype: PopupInfo url(components.js);
   display: block;
   ...
}
```
And script (components.js) 
```js
class PopupInfo extends Element 
{
   componentDidMount() {
      this.append(<span.info>{...}</span>,
                          <span.icon><img src={...}/></span> );
   }
   ["on mouseup"](event) { // mouseup handler 
       this.classList.toggle("visible");
       return false;
   }
}
```
This way you just need CSS to wire your DOM with script.

So CSS can be used not just defining presentational styles but also behavioral styles too. Presentational and behavioral styles are usually closely tied.
