### ISSUE TITLE
Can't change element styles from JavaScript

### ISSUE THREAD

**Issue by GirkovArpa** [c-smile/sciter-js-sdk#5]
I'm trying to implement the [7GUIs](https://eugenkiss.github.io/7guis/tasks) benchmarks with SciterJS, but I've run into the problem that I can't seem to change the style.

In [this](https://github.com/GirkovArpa/sciter-js-7guis/blob/master/flight-booker/script.js) code I'm trying to make the input background color red:

```javascript
'use strict';

const inputs = [...document.querySelectorAll('input[type=text]')];
const [inputStart, inputReturn] = inputs;

inputs.forEach((input) => {
  input.addEventListener('change', () => {
    const [day, month, year] = input.value.split('.');
    const date = new Date(year, month, day);
  
    if (date == 'Invalid Date') {
      // trying to change background color to red

      //input.style.backgroundColor = 'red'; // cannot set property 'backgroundColor' of undefined
      //input.classList.add('invalid'); // cannot read property 'add' of undefined
      //input.setAttribute('style', 'background-color: red'); // not a function
    } else {

    }
  });
});
```

I don't understand why `.setAttribute` isn't working since it's marked as `implemented` [here](https://github.com/c-smile/sciter-js-sdk/blob/main/status.md).

I also tried `input.className = 'date invalid'` but I get the error that there isn't a setter for this property.

Is it possible to modify an element's styles in JavaScript using SciterJS yet?

**Comment by jsprog** [comment]
All the problems mentioned above are tested to work. Likely you're not waiting for the DOM to get ready.

Sciter.js is new and some features are being added by time. I planned to rise an issue about element.style.setProperty but it's available as a string property instead of a function and likely it'll land very soon.

Note: you could still patch document.createElement and replace element.style.setProperty with your own implementation using element.style[propertyName], but pay attention to differences (e.g: backgroundColor instead of background-color)

**Comment by GirkovArpa** [comment]
You're right, I tried `document.querySelector('body').style.backgroundColor = 'red';` at the top of the script and it worked.
