### ISSUE TITLE
window not defined

### ISSUE THREAD

**Issue by Ksengine** [c-smile/sciter-js-sdk#6]
this is my console log:
`error:script: ReferenceError: 'window' is not defined`

no `window` object
is it `Window`?
please add  `window` object

**Comment by c-smile** [comment]
ES6 defines ```globalThis```  as the name of global namespace object.

In browsers, for some unknown to me reasons, they used name ```window``` for the global namespace object.

So if you need that then define:

```JavaScript
const window = globalThis;
```
before code that relies on ```window``` existence.

**Comment by Ksengine** [comment]
`window` object = BOM(browser object model)
has `globalThis` object methods and properties like `window` object

**Comment by c-smile** [comment]
In Sciter.JS window is a real window  - that thing that appear on desktop - instance of Window class.

Instance of the window where document is loaded is ```Window.this``` variable.

And so 
```
Window.this.move(0,0,800,600); 
var otherWindow = new Window({ ... });
otherWindow.move(300,400);
```
As of globalThis in Sciter...

It contains all methods you would expect in global namespace: setTimeout, clearTimeout, etc.
And so this will work:
```
const window = globalThis;

window.setTimout(function() {...},1000);
```

**Comment by Ksengine** [comment]
i want to use sciter as a webview.
it should show websites without errors

**Comment by jsprog** [comment]
**Disclaimer: I'm writing this for sharing, I'm not connected with the holders of Sciter.js in anyway nor affiliated with them.**

> i want to use sciter as a webview.

The window object is available starting from the last release. It should help in bringing maximum compatibility with existing javascript libraries and DOM.
Bundlers are taking care with most libraries to behave with browsers or node.js runtime. Not sure if we need a method to force some libraries relying on inspection for some objects (e.g: window) to behave running in the browser or node.js (e.g: setting a flag before invoking a dynamic import).


> it should show websites **without errors**

Making Sciter.js a web browser will just bloat it. Instead let's discuss some possible scenarios needed by your app:
- **You need to browse any random website:** Just use your web browser.
- **Maybe, your customer is a lawyer and needed to access a login page provided by the ministry of justice:** Ask your OS to open the url using the default web browser. You many even take a bigger step and use some services or extract the needed information without opening a webview at all.

Some other micro alternatives are depending on platform's browser and you need to worry about consistent rendering across different platforms, and the OS updates changing the rendering engine. I'd rather scratch my head a little bit when coding instead of closing my phone to avoid my customers. Not a long time ago, Microsoft updated edge to edge2 (chromium), and some historical updates broke the browser:
- [https://forums.windowscentral.com/ask-question/499574-anyone-elses-edge-broken-after-todays-update.html](https://forums.windowscentral.com/ask-question/499574-anyone-elses-edge-broken-after-todays-update.html)
- [https://answers.microsoft.com/en-us/microsoftedge/forum/all/edge-update-messed-up/cc8bceb0-c923-4507-830f-7dd8106d8a6a](https://answers.microsoft.com/en-us/microsoftedge/forum/all/edge-update-messed-up/cc8bceb0-c923-4507-830f-7dd8106d8a6a)
- [https://answers.microsoft.com/en-us/windows/forum/windows_10-update-winpc/kb4019472-update-broke-edge-and-other-applications/3def9623-c1aa-4f70-a292-19179bdf0719](https://answers.microsoft.com/en-us/windows/forum/windows_10-update-winpc/kb4019472-update-broke-edge-and-other-applications/3def9623-c1aa-4f70-a292-19179bdf0719)

I understand that some beautiful libraries for components are using CSS3 for flex box and transitions. Sciter is using a different syntax and rollup + postcss may fix some of them. I already used many of these libraries for coding some projects but I kicked nearly all of them due to these reasons:
- I had to force different styles (hacks) for some components and the updates were breaking my changes.
- Designing app components based on the ones provided by the libraries is simple, but the moment you start hacking them to force them to behave in the way you needed to is a different story. My clients should't be forced to use the mouse if they wanted to use the keyboard, and the updates to these libraries were breaking the hacks for fixing focus and keyboard navigation.
- usually, you only need a subset of what's provided by these libraries and designing your own components would be simple if you used a reactive framework (e.g: svelte). It takes some time at first, but no library will break your work.


Let's investigate more but opening the **Application Tab** from **chrome's developer tools** and see what's available:

**Cache Storage:** We don't need to catch what we have.

**Background Services (Notifications, etc...)**: Let's here from @c-smile 

**Manifest + Service Workers + Application Cache**:
You may need them for offline application with support for online update. Normally, you ship your app bundled with the scripts and assets. But if you're seeking online updates, just ship the small one you built, or inject the scripts + styles + assets at runtime. I already experienced this with nwjs and used rollup and postcss to bundle everything into a single file. For the moment, let's focus on the support for **base64 assets (fonts + images)** and the **injection of scripts and styles at runtime**.

**localStorage + indexeddb**:
You may use some other alternatives like sqlite, leveldb, lmdb, libmdbx, etc.
If you really needed browser's storage because a library required it, be aware that most libraries degrade gracefully to use what supported by your platform, and you only need to emulate localStorage. Emulation for localStorage is quite challenging and you need to synchronously block `localStorage.set` and `localStorage.get` (i.e: main script is blocked and a different thread is involved).

**Cookies:** emulate this if you need it and it's quite simple. I can't say too much about the Fetch API with Cookies and there is a discussion at [https://stackoverflow.com/questions/34558264/fetch-api-with-cookie](https://stackoverflow.com/questions/34558264/fetch-api-with-cookie)

**Comment by Ksengine** [comment]
That means i cant use sciter as a simple webview

**Comment by jsprog** [comment]
> That means i cant use sciter as a simple webview

1. When you surf the internet, you use one of the popular browsers.
2. When a web developer try to develop a native app for desktops or mobile phones, he'll try to achieve his goal with minimal efforts by using what he already know. for the user interface, he'll seek rendering, not browsing. And Sciter.js should help web developers to feel at home.

**Please answer my questions:**
1. Why web developers are using [react native](https://reactnative.dev/) and [nativescript](https://nativescript.org/)?
2. What are you trying to achieve?
3. Could you elaborate how the current approach is restricting you?

**Comment by Ksengine** [comment]
I want to use sciter as webview on python(without pysciter). so I want many features

**Comment by jsprog** [comment]
Please, have some manners and change your altitude. I won't answer your last post for these reasons:

1. You're not reading my posts.
2. You're acting as our boss by only giving instructions and not listening to what we are saying, nor answering our questions, nor stating your use cases or 
 your requirements. Many people will avoid you like this.
3. @c-smile responded to your request and the window object is there. I advice you to spend some time testing with the window object to report back your findings **or at least close this issue as it's solved**.

**Comment by Ksengine** [comment]
Sorry for my bad replies

**Comment by Ksengine** [comment]
I like to contribute and improve this.

**Comment by c-smile** [comment]
> it should show websites without errors

Set of websites is infinite and so no browser in existence is able to "show websites without errors". Even theoretically.
You will need to limit your scope somehow. 

> a simple webview

Could you explain meaning of this phrase in your context?  Both words please, "simple" and "webview".

**Comment by c-smile** [comment]
> I like to contribute and improve this.

How and what do you want to contribute? And what exactly you want to improve?
